#include "InputEvent.hpp"
#include <iostream>
#include <glfw3.h>

std::map<InputEvent::InputEventKey, std::string> InputEvent::eventKeyDescriptions = {
	{InputEvent::IEK_KEY_UNKNOWN, "IEK_KEY_UNKNOWN"},
	{InputEvent::IEK_KEY_SPACE, "IEK_KEY_SPACE"},
	{InputEvent::IEK_KEY_APOSTROPHE, "IEK_KEY_APOSTROPHE"},
	{InputEvent::IEK_KEY_COMMA, "IEK_KEY_COMMA"},
	{InputEvent::IEK_KEY_MINUS, "IEK_KEY_MINUS"},
	{InputEvent::IEK_KEY_PERIOD, "IEK_KEY_PERIOD"},
	{InputEvent::IEK_KEY_SLASH, "IEK_KEY_SLASH"},
	{InputEvent::IEK_KEY_0, "IEK_KEY_0"},
	{InputEvent::IEK_KEY_1, "IEK_KEY_1"},
	{InputEvent::IEK_KEY_2, "IEK_KEY_2"},
	{InputEvent::IEK_KEY_3, "IEK_KEY_3"},
	{InputEvent::IEK_KEY_4, "IEK_KEY_4"},
	{InputEvent::IEK_KEY_5, "IEK_KEY_5"},
	{InputEvent::IEK_KEY_6, "IEK_KEY_6"},
	{InputEvent::IEK_KEY_7, "IEK_KEY_7"},
	{InputEvent::IEK_KEY_8, "IEK_KEY_8"},
	{InputEvent::IEK_KEY_9, "IEK_KEY_9"},
	{InputEvent::IEK_KEY_SEMICOLON, "IEK_KEY_SEMICOLON"},
	{InputEvent::IEK_KEY_EQUAL, "IEK_KEY_EQUAL"},
	{InputEvent::IEK_KEY_A, "IEK_KEY_A"},
	{InputEvent::IEK_KEY_B, "IEK_KEY_B"},
	{InputEvent::IEK_KEY_C, "IEK_KEY_C"},
	{InputEvent::IEK_KEY_D, "IEK_KEY_D"},
	{InputEvent::IEK_KEY_E, "IEK_KEY_E"},
	{InputEvent::IEK_KEY_F, "IEK_KEY_F"},
	{InputEvent::IEK_KEY_G, "IEK_KEY_G"},
	{InputEvent::IEK_KEY_H, "IEK_KEY_H"},
	{InputEvent::IEK_KEY_I, "IEK_KEY_I"},
	{InputEvent::IEK_KEY_J, "IEK_KEY_J"},
	{InputEvent::IEK_KEY_K, "IEK_KEY_K"},
	{InputEvent::IEK_KEY_L, "IEK_KEY_L"},
	{InputEvent::IEK_KEY_M, "IEK_KEY_M"},
	{InputEvent::IEK_KEY_N, "IEK_KEY_N"},
	{InputEvent::IEK_KEY_O, "IEK_KEY_O"},
	{InputEvent::IEK_KEY_P, "IEK_KEY_P"},
	{InputEvent::IEK_KEY_Q, "IEK_KEY_Q"},
	{InputEvent::IEK_KEY_R, "IEK_KEY_R"},
	{InputEvent::IEK_KEY_S, "IEK_KEY_S"},
	{InputEvent::IEK_KEY_T, "IEK_KEY_T"},
	{InputEvent::IEK_KEY_U, "IEK_KEY_U"},
	{InputEvent::IEK_KEY_V, "IEK_KEY_V"},
	{InputEvent::IEK_KEY_W, "IEK_KEY_W"},
	{InputEvent::IEK_KEY_X, "IEK_KEY_X"},
	{InputEvent::IEK_KEY_Y, "IEK_KEY_Y"},
	{InputEvent::IEK_KEY_Z, "IEK_KEY_Z"},
	{InputEvent::IEK_KEY_LEFT_BRACKET, "IEK_KEY_LEFT_BRACKET"},
	{InputEvent::IEK_KEY_BACKSLASH, "IEK_KEY_BACKSLASH"},
	{InputEvent::IEK_KEY_RIGHT_BRACKET, "IEK_KEY_RIGHT_BRACKET"},
	{InputEvent::IEK_KEY_GRAVE_ACCENT, "IEK_KEY_GRAVE_ACCENT"},
	{InputEvent::IEK_KEY_WORLD_1, "IEK_KEY_WORLD_1"},
	{InputEvent::IEK_KEY_WORLD_2, "IEK_KEY_WORLD_2"},
	{InputEvent::IEK_KEY_ESCAPE, "IEK_KEY_ESCAPE"},
	{InputEvent::IEK_KEY_ENTER, "IEK_KEY_ENTER"},
	{InputEvent::IEK_KEY_TAB, "IEK_KEY_TAB"},
	{InputEvent::IEK_KEY_BACKSPACE, "IEK_KEY_BACKSPACE"},
	{InputEvent::IEK_KEY_INSERT, "IEK_KEY_INSERT"},
	{InputEvent::IEK_KEY_DELETE, "IEK_KEY_DELETE"},
	{InputEvent::IEK_KEY_RIGHT, "IEK_KEY_RIGHT"},
	{InputEvent::IEK_KEY_LEFT, "IEK_KEY_LEFT"},
	{InputEvent::IEK_KEY_DOWN, "IEK_KEY_DOWN"},
	{InputEvent::IEK_KEY_UP, "IEK_KEY_UP"},
	{InputEvent::IEK_KEY_PAGE_UP, "IEK_KEY_PAGE_UP"},
	{InputEvent::IEK_KEY_PAGE_DOWN, "IEK_KEY_PAGE_DOWN"},
	{InputEvent::IEK_KEY_HOME, "IEK_KEY_HOME"},
	{InputEvent::IEK_KEY_END, "IEK_KEY_END"},
	{InputEvent::IEK_KEY_CAPS_LOCK, "IEK_KEY_CAPS_LOCK"},
	{InputEvent::IEK_KEY_SCROLL_LOCK, "IEK_KEY_SCROLL_LOCK"},
	{InputEvent::IEK_KEY_NUM_LOCK, "IEK_KEY_NUM_LOCK"},
	{InputEvent::IEK_KEY_PRINT_SCREEN, "IEK_KEY_PRINT_SCREEN"},
	{InputEvent::IEK_KEY_PAUSE, "IEK_KEY_PAUSE"},
	{InputEvent::IEK_KEY_F1, "IEK_KEY_F1"},
	{InputEvent::IEK_KEY_F2, "IEK_KEY_F2"},
	{InputEvent::IEK_KEY_F3, "IEK_KEY_F3"},
	{InputEvent::IEK_KEY_F4, "IEK_KEY_F4"},
	{InputEvent::IEK_KEY_F5, "IEK_KEY_F5"},
	{InputEvent::IEK_KEY_F6, "IEK_KEY_F6"},
	{InputEvent::IEK_KEY_F7, "IEK_KEY_F7"},
	{InputEvent::IEK_KEY_F8, "IEK_KEY_F8"},
	{InputEvent::IEK_KEY_F9, "IEK_KEY_F9"},
	{InputEvent::IEK_KEY_F10, "IEK_KEY_F10"},
	{InputEvent::IEK_KEY_F11, "IEK_KEY_F11"},
	{InputEvent::IEK_KEY_F12, "IEK_KEY_F12"},
	{InputEvent::IEK_KEY_F13, "IEK_KEY_F13"},
	{InputEvent::IEK_KEY_F14, "IEK_KEY_F14"},
	{InputEvent::IEK_KEY_F15, "IEK_KEY_F15"},
	{InputEvent::IEK_KEY_F16, "IEK_KEY_F16"},
	{InputEvent::IEK_KEY_F17, "IEK_KEY_F17"},
	{InputEvent::IEK_KEY_F18, "IEK_KEY_F18"},
	{InputEvent::IEK_KEY_F19, "IEK_KEY_F19"},
	{InputEvent::IEK_KEY_F20, "IEK_KEY_F20"},
	{InputEvent::IEK_KEY_F21, "IEK_KEY_F21"},
	{InputEvent::IEK_KEY_F22, "IEK_KEY_F22"},
	{InputEvent::IEK_KEY_F23, "IEK_KEY_F23"},
	{InputEvent::IEK_KEY_F24, "IEK_KEY_F24"},
	{InputEvent::IEK_KEY_F25, "IEK_KEY_F25"},
	{InputEvent::IEK_KEY_KP_0, "IEK_KEY_KP_0"},
	{InputEvent::IEK_KEY_KP_1, "IEK_KEY_KP_1"},
	{InputEvent::IEK_KEY_KP_2, "IEK_KEY_KP_2"},
	{InputEvent::IEK_KEY_KP_3, "IEK_KEY_KP_3"},
	{InputEvent::IEK_KEY_KP_4, "IEK_KEY_KP_4"},
	{InputEvent::IEK_KEY_KP_5, "IEK_KEY_KP_5"},
	{InputEvent::IEK_KEY_KP_6, "IEK_KEY_KP_6"},
	{InputEvent::IEK_KEY_KP_7, "IEK_KEY_KP_7"},
	{InputEvent::IEK_KEY_KP_8, "IEK_KEY_KP_8"},
	{InputEvent::IEK_KEY_KP_9, "IEK_KEY_KP_9"},
	{InputEvent::IEK_KEY_KP_DECIMAL, "IEK_KEY_KP_DECIMAL"},
	{InputEvent::IEK_KEY_KP_DIVIDE, "IEK_KEY_KP_DIVIDE"},
	{InputEvent::IEK_KEY_KP_MULTIPLY, "IEK_KEY_KP_MULTIPLY"},
	{InputEvent::IEK_KEY_KP_SUBTRACT, "IEK_KEY_KP_SUBTRACT"},
	{InputEvent::IEK_KEY_KP_ADD, "IEK_KEY_KP_ADD"},
	{InputEvent::IEK_KEY_KP_ENTER, "IEK_KEY_KP_ENTER"},
	{InputEvent::IEK_KEY_KP_EQUAL, "IEK_KEY_KP_EQUAL"},
	{InputEvent::IEK_KEY_LEFT_SHIFT, "IEK_KEY_LEFT_SHIFT"},
	{InputEvent::IEK_KEY_LEFT_CONTROL, "IEK_KEY_LEFT_CONTROL"},
	{InputEvent::IEK_KEY_LEFT_ALT, "IEK_KEY_LEFT_ALT"},
	{InputEvent::IEK_KEY_LEFT_SUPER, "IEK_KEY_LEFT_SUPER"},
	{InputEvent::IEK_KEY_RIGHT_SHIFT, "IEK_KEY_RIGHT_SHIFT"},
	{InputEvent::IEK_KEY_RIGHT_CONTROL, "IEK_KEY_RIGHT_CONTROL"},
	{InputEvent::IEK_KEY_RIGHT_ALT, "IEK_KEY_RIGHT_ALT"},
	{InputEvent::IEK_KEY_RIGHT_SUPER, "IEK_KEY_RIGHT_SUPER"},
	{InputEvent::IEK_KEY_MENU, "IEK_KEY_MENU"},
	{InputEvent::IEK_MOUSE_BUTTON_1, "IEK_MOUSE_BUTTON_1"},
	{InputEvent::IEK_MOUSE_BUTTON_2, "IEK_MOUSE_BUTTON_2"},
	{InputEvent::IEK_MOUSE_BUTTON_3, "IEK_MOUSE_BUTTON_3"},
	{InputEvent::IEK_MOUSE_BUTTON_4, "IEK_MOUSE_BUTTON_4"},
	{InputEvent::IEK_MOUSE_BUTTON_5, "IEK_MOUSE_BUTTON_5"},
	{InputEvent::IEK_MOUSE_BUTTON_6, "IEK_MOUSE_BUTTON_6"},
	{InputEvent::IEK_MOUSE_BUTTON_7, "IEK_MOUSE_BUTTON_7"},
	{InputEvent::IEK_MOUSE_BUTTON_8, "IEK_MOUSE_BUTTON_8"},
	{InputEvent::IEK_MOUSE_MOVE, "IEK_MOUSE_MOVE"}
};

std::map<InputEvent::InputEventKeyState, std::string> InputEvent::eventKeyStateDescriptions = {
	{InputEvent::IEKS_NO_STATE, "IEKS_NO_STATE" },
	{InputEvent::IEKS_PRESS, "IEKS_PRESS"},
	{InputEvent::IEKS_RELEASE, "IEKS_RELEASE"},
	{InputEvent::IEKS_REPEAT, "IEKS_REPEAT"}
};

std::map<int, InputEvent::InputEventKey> InputEvent::glfwKeyTranslations = {
	{GLFW_KEY_UNKNOWN, InputEvent::IEK_KEY_UNKNOWN},
	{GLFW_KEY_SPACE, InputEvent::IEK_KEY_SPACE},
	{GLFW_KEY_APOSTROPHE, InputEvent::IEK_KEY_APOSTROPHE},
	{GLFW_KEY_COMMA, InputEvent::IEK_KEY_COMMA},
	{GLFW_KEY_MINUS, InputEvent::IEK_KEY_MINUS},
	{GLFW_KEY_PERIOD, InputEvent::IEK_KEY_PERIOD},
	{GLFW_KEY_SLASH, InputEvent::IEK_KEY_SLASH},
	{GLFW_KEY_0, InputEvent::IEK_KEY_0},
	{GLFW_KEY_1, InputEvent::IEK_KEY_1},
	{GLFW_KEY_2, InputEvent::IEK_KEY_2},
	{GLFW_KEY_3, InputEvent::IEK_KEY_3},
	{GLFW_KEY_4, InputEvent::IEK_KEY_4},
	{GLFW_KEY_5, InputEvent::IEK_KEY_5},
	{GLFW_KEY_6, InputEvent::IEK_KEY_6},
	{GLFW_KEY_7, InputEvent::IEK_KEY_7},
	{GLFW_KEY_8, InputEvent::IEK_KEY_8},
	{GLFW_KEY_9, InputEvent::IEK_KEY_9},
	{GLFW_KEY_SEMICOLON, InputEvent::IEK_KEY_SEMICOLON},
	{GLFW_KEY_EQUAL, InputEvent::IEK_KEY_EQUAL},
	{GLFW_KEY_A, InputEvent::IEK_KEY_A},
	{GLFW_KEY_B, InputEvent::IEK_KEY_B},
	{GLFW_KEY_C, InputEvent::IEK_KEY_C},
	{GLFW_KEY_D, InputEvent::IEK_KEY_D},
	{GLFW_KEY_E, InputEvent::IEK_KEY_E},
	{GLFW_KEY_F, InputEvent::IEK_KEY_F},
	{GLFW_KEY_G, InputEvent::IEK_KEY_G},
	{GLFW_KEY_H, InputEvent::IEK_KEY_H},
	{GLFW_KEY_I, InputEvent::IEK_KEY_I},
	{GLFW_KEY_J, InputEvent::IEK_KEY_J},
	{GLFW_KEY_K, InputEvent::IEK_KEY_K},
	{GLFW_KEY_L, InputEvent::IEK_KEY_L},
	{GLFW_KEY_M, InputEvent::IEK_KEY_M},
	{GLFW_KEY_N, InputEvent::IEK_KEY_N},
	{GLFW_KEY_O, InputEvent::IEK_KEY_O},
	{GLFW_KEY_P, InputEvent::IEK_KEY_P},
	{GLFW_KEY_Q, InputEvent::IEK_KEY_Q},
	{GLFW_KEY_R, InputEvent::IEK_KEY_R},
	{GLFW_KEY_S, InputEvent::IEK_KEY_S},
	{GLFW_KEY_T, InputEvent::IEK_KEY_T},
	{GLFW_KEY_U, InputEvent::IEK_KEY_U},
	{GLFW_KEY_V, InputEvent::IEK_KEY_V},
	{GLFW_KEY_W, InputEvent::IEK_KEY_W},
	{GLFW_KEY_X, InputEvent::IEK_KEY_X},
	{GLFW_KEY_Y, InputEvent::IEK_KEY_Y},
	{GLFW_KEY_Z, InputEvent::IEK_KEY_Z},
	{GLFW_KEY_LEFT_BRACKET, InputEvent::IEK_KEY_LEFT_BRACKET},
	{GLFW_KEY_BACKSLASH, InputEvent::IEK_KEY_BACKSLASH},
	{GLFW_KEY_RIGHT_BRACKET, InputEvent::IEK_KEY_RIGHT_BRACKET},
	{GLFW_KEY_GRAVE_ACCENT, InputEvent::IEK_KEY_GRAVE_ACCENT},
	{GLFW_KEY_WORLD_1, InputEvent::IEK_KEY_WORLD_1},
	{GLFW_KEY_WORLD_2, InputEvent::IEK_KEY_WORLD_2},
	{GLFW_KEY_ESCAPE, InputEvent::IEK_KEY_ESCAPE},
	{GLFW_KEY_ENTER, InputEvent::IEK_KEY_ENTER},
	{GLFW_KEY_TAB, InputEvent::IEK_KEY_TAB},
	{GLFW_KEY_BACKSPACE, InputEvent::IEK_KEY_BACKSPACE},
	{GLFW_KEY_INSERT, InputEvent::IEK_KEY_INSERT},
	{GLFW_KEY_DELETE, InputEvent::IEK_KEY_DELETE},
	{GLFW_KEY_RIGHT, InputEvent::IEK_KEY_RIGHT},
	{GLFW_KEY_LEFT, InputEvent::IEK_KEY_LEFT},
	{GLFW_KEY_DOWN, InputEvent::IEK_KEY_DOWN},
	{GLFW_KEY_UP, InputEvent::IEK_KEY_UP},
	{GLFW_KEY_PAGE_UP, InputEvent::IEK_KEY_PAGE_UP},
	{GLFW_KEY_PAGE_DOWN, InputEvent::IEK_KEY_PAGE_DOWN},
	{GLFW_KEY_HOME, InputEvent::IEK_KEY_HOME},
	{GLFW_KEY_END, InputEvent::IEK_KEY_END},
	{GLFW_KEY_CAPS_LOCK, InputEvent::IEK_KEY_CAPS_LOCK},
	{GLFW_KEY_SCROLL_LOCK, InputEvent::IEK_KEY_SCROLL_LOCK},
	{GLFW_KEY_NUM_LOCK, InputEvent::IEK_KEY_NUM_LOCK},
	{GLFW_KEY_PRINT_SCREEN, InputEvent::IEK_KEY_PRINT_SCREEN},
	{GLFW_KEY_PAUSE, InputEvent::IEK_KEY_PAUSE},
	{GLFW_KEY_F1, InputEvent::IEK_KEY_F1},
	{GLFW_KEY_F2, InputEvent::IEK_KEY_F2},
	{GLFW_KEY_F3, InputEvent::IEK_KEY_F3},
	{GLFW_KEY_F4, InputEvent::IEK_KEY_F4},
	{GLFW_KEY_F5, InputEvent::IEK_KEY_F5},
	{GLFW_KEY_F6, InputEvent::IEK_KEY_F6},
	{GLFW_KEY_F7, InputEvent::IEK_KEY_F7},
	{GLFW_KEY_F8, InputEvent::IEK_KEY_F8},
	{GLFW_KEY_F9, InputEvent::IEK_KEY_F9},
	{GLFW_KEY_F10, InputEvent::IEK_KEY_F10},
	{GLFW_KEY_F11, InputEvent::IEK_KEY_F11},
	{GLFW_KEY_F12, InputEvent::IEK_KEY_F12},
	{GLFW_KEY_F13, InputEvent::IEK_KEY_F13},
	{GLFW_KEY_F14, InputEvent::IEK_KEY_F14},
	{GLFW_KEY_F15, InputEvent::IEK_KEY_F15},
	{GLFW_KEY_F16, InputEvent::IEK_KEY_F16},
	{GLFW_KEY_F17, InputEvent::IEK_KEY_F17},
	{GLFW_KEY_F18, InputEvent::IEK_KEY_F18},
	{GLFW_KEY_F19, InputEvent::IEK_KEY_F19},
	{GLFW_KEY_F20, InputEvent::IEK_KEY_F20},
	{GLFW_KEY_F21, InputEvent::IEK_KEY_F21},
	{GLFW_KEY_F22, InputEvent::IEK_KEY_F22},
	{GLFW_KEY_F23, InputEvent::IEK_KEY_F23},
	{GLFW_KEY_F24, InputEvent::IEK_KEY_F24},
	{GLFW_KEY_F25, InputEvent::IEK_KEY_F25},
	{GLFW_KEY_KP_0, InputEvent::IEK_KEY_KP_0},
	{GLFW_KEY_KP_1, InputEvent::IEK_KEY_KP_1},
	{GLFW_KEY_KP_2, InputEvent::IEK_KEY_KP_2},
	{GLFW_KEY_KP_3, InputEvent::IEK_KEY_KP_3},
	{GLFW_KEY_KP_4, InputEvent::IEK_KEY_KP_4},
	{GLFW_KEY_KP_5, InputEvent::IEK_KEY_KP_5},
	{GLFW_KEY_KP_6, InputEvent::IEK_KEY_KP_6},
	{GLFW_KEY_KP_7, InputEvent::IEK_KEY_KP_7},
	{GLFW_KEY_KP_8, InputEvent::IEK_KEY_KP_8},
	{GLFW_KEY_KP_9, InputEvent::IEK_KEY_KP_9},
	{GLFW_KEY_KP_DECIMAL, InputEvent::IEK_KEY_KP_DECIMAL},
	{GLFW_KEY_KP_DIVIDE, InputEvent::IEK_KEY_KP_DIVIDE},
	{GLFW_KEY_KP_MULTIPLY, InputEvent::IEK_KEY_KP_MULTIPLY},
	{GLFW_KEY_KP_SUBTRACT, InputEvent::IEK_KEY_KP_SUBTRACT},
	{GLFW_KEY_KP_ADD, InputEvent::IEK_KEY_KP_ADD},
	{GLFW_KEY_KP_ENTER, InputEvent::IEK_KEY_KP_ENTER},
	{GLFW_KEY_KP_EQUAL, InputEvent::IEK_KEY_KP_EQUAL},
	{GLFW_KEY_LEFT_SHIFT, InputEvent::IEK_KEY_LEFT_SHIFT},
	{GLFW_KEY_LEFT_CONTROL, InputEvent::IEK_KEY_LEFT_CONTROL},
	{GLFW_KEY_LEFT_ALT, InputEvent::IEK_KEY_LEFT_ALT},
	{GLFW_KEY_LEFT_SUPER, InputEvent::IEK_KEY_LEFT_SUPER},
	{GLFW_KEY_RIGHT_SHIFT, InputEvent::IEK_KEY_RIGHT_SHIFT},
	{GLFW_KEY_RIGHT_CONTROL, InputEvent::IEK_KEY_RIGHT_CONTROL},
	{GLFW_KEY_RIGHT_ALT, InputEvent::IEK_KEY_RIGHT_ALT},
	{GLFW_KEY_RIGHT_SUPER, InputEvent::IEK_KEY_RIGHT_SUPER},
	{GLFW_KEY_MENU, InputEvent::IEK_KEY_MENU},
	{GLFW_MOUSE_BUTTON_1, InputEvent::IEK_MOUSE_BUTTON_1},
	{GLFW_MOUSE_BUTTON_2, InputEvent::IEK_MOUSE_BUTTON_2},
	{GLFW_MOUSE_BUTTON_3, InputEvent::IEK_MOUSE_BUTTON_3},
	{GLFW_MOUSE_BUTTON_4, InputEvent::IEK_MOUSE_BUTTON_4},
	{GLFW_MOUSE_BUTTON_5, InputEvent::IEK_MOUSE_BUTTON_5},
	{GLFW_MOUSE_BUTTON_6, InputEvent::IEK_MOUSE_BUTTON_6},
	{GLFW_MOUSE_BUTTON_7, InputEvent::IEK_MOUSE_BUTTON_7},
	{GLFW_MOUSE_BUTTON_8, InputEvent::IEK_MOUSE_BUTTON_8},
	{GLFW_MOUSE_BUTTON_LEFT, InputEvent::IEK_MOUSE_BUTTON_1},
	{GLFW_MOUSE_BUTTON_RIGHT, InputEvent::IEK_MOUSE_BUTTON_2},
	{GLFW_MOUSE_BUTTON_MIDDLE, InputEvent::IEK_MOUSE_BUTTON_3}
};

std::map<int, InputEvent::InputEventKeyState> InputEvent::glfwKeyStateTranslations = {
	{GLFW_PRESS, InputEvent::IEKS_PRESS},
	{GLFW_RELEASE, InputEvent::IEKS_RELEASE},
	{GLFW_REPEAT, InputEvent::IEKS_REPEAT}
};

std::string InputEvent::decodeInputEventKey(InputEventKey eventKey) {
	return eventKeyDescriptions[eventKey];
}

std::string InputEvent::decodeInputEventKeyState(InputEventKeyState eventKeyState) {
	return eventKeyStateDescriptions[eventKeyState];
}

InputEvent::InputEventKey InputEvent::translateGlfwInputEventKey(int glfwEventKey) {
	return glfwKeyTranslations[glfwEventKey];
}

InputEvent::InputEventKeyState InputEvent::translateGlfwInputEventKeyState(int glfwEventKeyState) {
	return glfwKeyStateTranslations[glfwEventKeyState];
}

void InputEvent::print() {
	std::cout << "------------------------------------------------" << std::endl;
	std::cout << "       Event Key: " << decodeInputEventKey(eventKey) << std::endl;
	std::cout << " Event Key State: " << decodeInputEventKeyState(eventKeyState) << std::endl;
	std::cout << "  Modifier Shift: " << modifierShift << std::endl;
	std::cout << "Modifier Control: " << modifierControl << std::endl;
	std::cout << "    Modifier Alt: " << modifierAlt << std::endl;
	std::cout << "  Modifier Super: " << modifierSuper << std::endl;
	std::cout << "    X Coordinate: " << xCoordinate << std::endl;
	std::cout << "    Y Coordinate: " << yCoordinate << std::endl;
}
